#lang racket

;; Builtin function names for different Hermes bytecode versions
;; Based on hermes-dec-main/src/parsers/hbc_opcodes/

(provide get-builtin-names
         get-builtin-name)

;; HBC version 84 and earlier builtin functions
(define builtin-names-v84
  '#("Array.isArray"
     "ArrayBuffer.isView"
     "Date.UTC"
     "Date.now"
     "Date.parse"
     "JSON.parse"
     "JSON.stringify"
     "Math.abs"
     "Math.acos"
     "Math.asin"
     "Math.atan"
     "Math.atan2"
     "Math.ceil"
     "Math.cos"
     "Math.exp"
     "Math.floor"
     "Math.hypot"
     "Math.imul"
     "Math.log"
     "Math.max"
     "Math.min"
     "Math.pow"
     "Math.random"
     "Math.round"
     "Math.sin"
     "Math.sqrt"
     "Math.tan"
     "Math.trunc"
     "Object.create"
     "Object.defineProperties"
     "Object.defineProperty"
     "Object.freeze"
     "Object.getOwnPropertyDescriptor"
     "Object.getOwnPropertyNames"
     "Object.getPrototypeOf"
     "Object.isExtensible"
     "Object.isFrozen"
     "Object.keys"
     "Object.seal"
     "String.fromCharCode"
     "silentSetPrototypeOf"
     "requireFast"
     "getTemplateObject"
     "ensureObject"
     "getMethod"
     "throwTypeError"
     "generatorSetDelegated"
     "copyDataProperties"
     "copyRestArgs"
     "arraySpread"
     "apply"
     "exportAll"
     "exponentiationOperator"))

;; HBC version 85-94 builtin functions
(define builtin-names-v85
  '#("Array.isArray"
     "Date.UTC"
     "Date.parse"
     "JSON.parse"
     "JSON.stringify"
     "Math.abs"
     "Math.acos"
     "Math.asin"
     "Math.atan"
     "Math.atan2"
     "Math.ceil"
     "Math.cos"
     "Math.exp"
     "Math.floor"
     "Math.hypot"
     "Math.imul"
     "Math.log"
     "Math.max"
     "Math.min"
     "Math.pow"
     "Math.round"
     "Math.sin"
     "Math.sqrt"
     "Math.tan"
     "Math.trunc"
     "Object.create"
     "Object.defineProperties"
     "Object.defineProperty"
     "Object.freeze"
     "Object.getOwnPropertyDescriptor"
     "Object.getOwnPropertyNames"
     "Object.getPrototypeOf"
     "Object.isExtensible"
     "Object.isFrozen"
     "Object.keys"
     "Object.seal"
     "String.fromCharCode"
     "silentSetPrototypeOf"
     "requireFast"
     "getTemplateObject"
     "ensureObject"
     "getMethod"
     "throwTypeError"
     "generatorSetDelegated"
     "copyDataProperties"
     "copyRestArgs"
     "arraySpread"
     "apply"
     "exportAll"
     "exponentiationOperator"))

;; HBC version 95+ builtin functions
(define builtin-names-v95
  '#("Array.isArray"
     "Date.UTC"
     "Date.parse"
     "JSON.parse"
     "JSON.stringify"
     "Math.abs"
     "Math.acos"
     "Math.asin"
     "Math.atan"
     "Math.atan2"
     "Math.ceil"
     "Math.cos"
     "Math.exp"
     "Math.floor"
     "Math.hypot"
     "Math.imul"
     "Math.log"
     "Math.max"
     "Math.min"
     "Math.pow"
     "Math.round"
     "Math.sin"
     "Math.sqrt"
     "Math.tan"
     "Math.trunc"
     "Object.create"
     "Object.defineProperties"
     "Object.defineProperty"
     "Object.freeze"
     "Object.getOwnPropertyDescriptor"
     "Object.getOwnPropertyNames"
     "Object.getPrototypeOf"
     "Object.isExtensible"
     "Object.isFrozen"
     "Object.keys"
     "Object.seal"
     "String.fromCharCode"
     "silentSetPrototypeOf"
     "requireFast"
     "getTemplateObject"
     "ensureObject"
     "getMethod"
     "throwTypeError"
     "generatorSetDelegated"
     "copyDataProperties"
     "copyRestArgs"
     "arraySpread"
     "apply"
     "exportAll"
     "exponentiationOperator"
     "initRegexNamedGroups"
     "getOriginalNativeErrorConstructor"
     "spawnAsync"))

;; Get builtin names vector for a given HBC version
(define (get-builtin-names ver)
  (cond
    [(<= ver 84) builtin-names-v84]
    [(<= ver 94) builtin-names-v85]
    [else builtin-names-v95]))

;; Get a single builtin function name by version and index
(define (get-builtin-name ver idx)
  (let ([names (get-builtin-names ver)])
    (if (and (integer? idx) (>= idx 0) (< idx (vector-length names)))
        (vector-ref names idx)
        (format "builtin_~a" idx))))
